Repository go-nv/goenv, pull requests merged in 2024-12, with the labels that each got.

#417 Add option to prepend or append shims directory to PATH
  ENVIRONMENT_VARIABLES.md
  libexec/goenv-init
  test/goenv-init.bats
Labels: chore

#419 Fix Issues From Previous Merges
  .github/CODEOWNERS
  libexec/goenv-init
  libexec/goenv-installed
  libexec/goenv-prefix
  libexec/goenv-version-file-write
  libexec/goenv-version-name
  test/goenv-global.bats
  test/goenv-init.bats
  test/goenv-local.bats
  test/goenv-version-file-write.bats
  test/goenv.bats
Labels: bug, chore

#421 Try and fix the perf issues with goenv installed
  libexec/goenv-installed
  test/goenv-help.bats
  test/test_helper.bash
Labels: bug

#422 Auto-pre-release
  .github/workflows/release-drafter.yml
Labels: chore

#427 short ciruit the loop if it's not executable
  .github/workflows/release-drafter.yml
  libexec/goenv-commands
Labels: chore

#431 goenv-init: Fix use of optional variables that should not crash the calling shell if unset
  libexec/goenv-init
  test/goenv-init.bats
Labels: bug
